/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RoleRouteImport } from './routes/role'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InstituteIndexRouteImport } from './routes/institute.index'
import { Route as InstituteAnalyticsRouteImport } from './routes/institute.analytics'
import { Route as InstituteAssessmentsRouteImport } from './routes/institute.assessments'
import { Route as InstituteClassesRouteImport } from './routes/institute.classes'
import { Route as InstituteCurriculumRouteImport } from './routes/institute.curriculum'
import { Route as InstituteReportsRouteImport } from './routes/institute.reports'
import { Route as InstituteStudentsRouteImport } from './routes/institute.students'
import { Route as InstituteTeachersRouteImport } from './routes/institute.teachers'
import { Route as OnboardingInstituteRouteImport } from './routes/onboarding.institute'
import { Route as OnboardingParentRouteImport } from './routes/onboarding.parent'
import { Route as OnboardingTeacherRouteImport } from './routes/onboarding.teacher'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentChildRouteImport } from './routes/parent.child'
import { Route as ParentFeedbackRouteImport } from './routes/parent.feedback'
import { Route as ParentHomeworkRouteImport } from './routes/parent.homework'
import { Route as ParentLearnRouteImport } from './routes/parent.learn'
import { Route as ParentLessonsRouteImport } from './routes/parent.lessons'
import { Route as ParentProgressRouteImport } from './routes/parent.progress'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as TeacherBlackboardRouteImport } from './routes/teacher.blackboard'
import { Route as TeacherCurriculumRouteImport } from './routes/teacher.curriculum'
import { Route as TeacherLanguageRouteImport } from './routes/teacher.language'
import { Route as TeacherLiveRouteImport } from './routes/teacher.live'
import { Route as TeacherMoreRouteImport } from './routes/teacher.more'
import { Route as TeacherOfflineRouteImport } from './routes/teacher.offline'
import { Route as TeacherProgressRouteImport } from './routes/teacher.progress'
import { Route as TeacherResourcesRouteImport } from './routes/teacher.resources'
import { Route as TeacherTranslateRouteImport } from './routes/teacher.translate'
import { Route as TeacherWorksheetsRouteImport } from './routes/teacher.worksheets'
import { Route as TeacherClassroomsIndexRouteImport } from './routes/teacher.classrooms.index'
import { Route as TeacherClassroomsClassroomIdRouteImport } from './routes/teacher.classrooms.$classroomId'
import { Route as TeacherClassroomsNewRouteImport } from './routes/teacher.classrooms.new'
import { Route as TeacherPlannerIndexRouteImport } from './routes/teacher.planner.index'
import { Route as TeacherPlannerPlanRouteImport } from './routes/teacher.planner.plan'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteIndexRoute = InstituteIndexRouteImport.update({
  id: '/institute/',
  path: '/institute/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteAnalyticsRoute = InstituteAnalyticsRouteImport.update({
  id: '/institute/analytics',
  path: '/institute/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteAssessmentsRoute = InstituteAssessmentsRouteImport.update({
  id: '/institute/assessments',
  path: '/institute/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteClassesRoute = InstituteClassesRouteImport.update({
  id: '/institute/classes',
  path: '/institute/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteCurriculumRoute = InstituteCurriculumRouteImport.update({
  id: '/institute/curriculum',
  path: '/institute/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteReportsRoute = InstituteReportsRouteImport.update({
  id: '/institute/reports',
  path: '/institute/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteStudentsRoute = InstituteStudentsRouteImport.update({
  id: '/institute/students',
  path: '/institute/students',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteTeachersRoute = InstituteTeachersRouteImport.update({
  id: '/institute/teachers',
  path: '/institute/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInstituteRoute = OnboardingInstituteRouteImport.update({
  id: '/onboarding/institute',
  path: '/onboarding/institute',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingParentRoute = OnboardingParentRouteImport.update({
  id: '/onboarding/parent',
  path: '/onboarding/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTeacherRoute = OnboardingTeacherRouteImport.update({
  id: '/onboarding/teacher',
  path: '/onboarding/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildRoute = ParentChildRouteImport.update({
  id: '/parent/child',
  path: '/parent/child',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentFeedbackRoute = ParentFeedbackRouteImport.update({
  id: '/parent/feedback',
  path: '/parent/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentHomeworkRoute = ParentHomeworkRouteImport.update({
  id: '/parent/homework',
  path: '/parent/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentLearnRoute = ParentLearnRouteImport.update({
  id: '/parent/learn',
  path: '/parent/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentLessonsRoute = ParentLessonsRouteImport.update({
  id: '/parent/lessons',
  path: '/parent/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/parent/progress',
  path: '/parent/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/teacher/assessments',
  path: '/teacher/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherBlackboardRoute = TeacherBlackboardRouteImport.update({
  id: '/teacher/blackboard',
  path: '/teacher/blackboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCurriculumRoute = TeacherCurriculumRouteImport.update({
  id: '/teacher/curriculum',
  path: '/teacher/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLanguageRoute = TeacherLanguageRouteImport.update({
  id: '/teacher/language',
  path: '/teacher/language',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLiveRoute = TeacherLiveRouteImport.update({
  id: '/teacher/live',
  path: '/teacher/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMoreRoute = TeacherMoreRouteImport.update({
  id: '/teacher/more',
  path: '/teacher/more',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherOfflineRoute = TeacherOfflineRouteImport.update({
  id: '/teacher/offline',
  path: '/teacher/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProgressRoute = TeacherProgressRouteImport.update({
  id: '/teacher/progress',
  path: '/teacher/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherResourcesRoute = TeacherResourcesRouteImport.update({
  id: '/teacher/resources',
  path: '/teacher/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTranslateRoute = TeacherTranslateRouteImport.update({
  id: '/teacher/translate',
  path: '/teacher/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherWorksheetsRoute = TeacherWorksheetsRouteImport.update({
  id: '/teacher/worksheets',
  path: '/teacher/worksheets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassroomsIndexRoute = TeacherClassroomsIndexRouteImport.update({
  id: '/teacher/classrooms/',
  path: '/teacher/classrooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassroomsClassroomIdRoute =
  TeacherClassroomsClassroomIdRouteImport.update({
    id: '/teacher/classrooms/$classroomId',
    path: '/teacher/classrooms/$classroomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherClassroomsNewRoute = TeacherClassroomsNewRouteImport.update({
  id: '/teacher/classrooms/new',
  path: '/teacher/classrooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPlannerIndexRoute = TeacherPlannerIndexRouteImport.update({
  id: '/teacher/planner/',
  path: '/teacher/planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPlannerPlanRoute = TeacherPlannerPlanRouteImport.update({
  id: '/teacher/planner/plan',
  path: '/teacher/planner/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/teacher/students/$studentId',
    path: '/teacher/students/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/institute/analytics': typeof InstituteAnalyticsRoute
  '/institute/assessments': typeof InstituteAssessmentsRoute
  '/institute/classes': typeof InstituteClassesRoute
  '/institute/curriculum': typeof InstituteCurriculumRoute
  '/institute/reports': typeof InstituteReportsRoute
  '/institute/students': typeof InstituteStudentsRoute
  '/institute/teachers': typeof InstituteTeachersRoute
  '/onboarding/institute': typeof OnboardingInstituteRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/onboarding/teacher': typeof OnboardingTeacherRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/learn': typeof ParentLearnRoute
  '/parent/lessons': typeof ParentLessonsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/blackboard': typeof TeacherBlackboardRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/language': typeof TeacherLanguageRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/offline': typeof TeacherOfflineRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/translate': typeof TeacherTranslateRoute
  '/teacher/worksheets': typeof TeacherWorksheetsRoute
  '/institute/': typeof InstituteIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classrooms/$classroomId': typeof TeacherClassroomsClassroomIdRoute
  '/teacher/classrooms/new': typeof TeacherClassroomsNewRoute
  '/teacher/planner/plan': typeof TeacherPlannerPlanRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/classrooms/': typeof TeacherClassroomsIndexRoute
  '/teacher/planner/': typeof TeacherPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/institute/analytics': typeof InstituteAnalyticsRoute
  '/institute/assessments': typeof InstituteAssessmentsRoute
  '/institute/classes': typeof InstituteClassesRoute
  '/institute/curriculum': typeof InstituteCurriculumRoute
  '/institute/reports': typeof InstituteReportsRoute
  '/institute/students': typeof InstituteStudentsRoute
  '/institute/teachers': typeof InstituteTeachersRoute
  '/onboarding/institute': typeof OnboardingInstituteRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/onboarding/teacher': typeof OnboardingTeacherRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/learn': typeof ParentLearnRoute
  '/parent/lessons': typeof ParentLessonsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/blackboard': typeof TeacherBlackboardRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/language': typeof TeacherLanguageRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/offline': typeof TeacherOfflineRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/translate': typeof TeacherTranslateRoute
  '/teacher/worksheets': typeof TeacherWorksheetsRoute
  '/institute': typeof InstituteIndexRoute
  '/parent': typeof ParentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/classrooms/$classroomId': typeof TeacherClassroomsClassroomIdRoute
  '/teacher/classrooms/new': typeof TeacherClassroomsNewRoute
  '/teacher/planner/plan': typeof TeacherPlannerPlanRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/classrooms': typeof TeacherClassroomsIndexRoute
  '/teacher/planner': typeof TeacherPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/institute/analytics': typeof InstituteAnalyticsRoute
  '/institute/assessments': typeof InstituteAssessmentsRoute
  '/institute/classes': typeof InstituteClassesRoute
  '/institute/curriculum': typeof InstituteCurriculumRoute
  '/institute/reports': typeof InstituteReportsRoute
  '/institute/students': typeof InstituteStudentsRoute
  '/institute/teachers': typeof InstituteTeachersRoute
  '/onboarding/institute': typeof OnboardingInstituteRoute
  '/onboarding/parent': typeof OnboardingParentRoute
  '/onboarding/teacher': typeof OnboardingTeacherRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/learn': typeof ParentLearnRoute
  '/parent/lessons': typeof ParentLessonsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/blackboard': typeof TeacherBlackboardRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/language': typeof TeacherLanguageRoute
  '/teacher/live': typeof TeacherLiveRoute
  '/teacher/more': typeof TeacherMoreRoute
  '/teacher/offline': typeof TeacherOfflineRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/translate': typeof TeacherTranslateRoute
  '/teacher/worksheets': typeof TeacherWorksheetsRoute
  '/institute/': typeof InstituteIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classrooms/$classroomId': typeof TeacherClassroomsClassroomIdRoute
  '/teacher/classrooms/new': typeof TeacherClassroomsNewRoute
  '/teacher/planner/plan': typeof TeacherPlannerPlanRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/classrooms/': typeof TeacherClassroomsIndexRoute
  '/teacher/planner/': typeof TeacherPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/login'
    | '/notifications'
    | '/role'
    | '/settings'
    | '/institute/analytics'
    | '/institute/assessments'
    | '/institute/classes'
    | '/institute/curriculum'
    | '/institute/reports'
    | '/institute/students'
    | '/institute/teachers'
    | '/onboarding/institute'
    | '/onboarding/parent'
    | '/onboarding/teacher'
    | '/parent/child'
    | '/parent/feedback'
    | '/parent/homework'
    | '/parent/learn'
    | '/parent/lessons'
    | '/parent/progress'
    | '/teacher/assessments'
    | '/teacher/blackboard'
    | '/teacher/curriculum'
    | '/teacher/language'
    | '/teacher/live'
    | '/teacher/more'
    | '/teacher/offline'
    | '/teacher/progress'
    | '/teacher/resources'
    | '/teacher/translate'
    | '/teacher/worksheets'
    | '/institute/'
    | '/parent/'
    | '/teacher/'
    | '/teacher/classrooms/$classroomId'
    | '/teacher/classrooms/new'
    | '/teacher/planner/plan'
    | '/teacher/students/$studentId'
    | '/teacher/classrooms/'
    | '/teacher/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/login'
    | '/notifications'
    | '/role'
    | '/settings'
    | '/institute/analytics'
    | '/institute/assessments'
    | '/institute/classes'
    | '/institute/curriculum'
    | '/institute/reports'
    | '/institute/students'
    | '/institute/teachers'
    | '/onboarding/institute'
    | '/onboarding/parent'
    | '/onboarding/teacher'
    | '/parent/child'
    | '/parent/feedback'
    | '/parent/homework'
    | '/parent/learn'
    | '/parent/lessons'
    | '/parent/progress'
    | '/teacher/assessments'
    | '/teacher/blackboard'
    | '/teacher/curriculum'
    | '/teacher/language'
    | '/teacher/live'
    | '/teacher/more'
    | '/teacher/offline'
    | '/teacher/progress'
    | '/teacher/resources'
    | '/teacher/translate'
    | '/teacher/worksheets'
    | '/institute'
    | '/parent'
    | '/teacher'
    | '/teacher/classrooms/$classroomId'
    | '/teacher/classrooms/new'
    | '/teacher/planner/plan'
    | '/teacher/students/$studentId'
    | '/teacher/classrooms'
    | '/teacher/planner'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/help'
    | '/login'
    | '/notifications'
    | '/role'
    | '/settings'
    | '/institute/analytics'
    | '/institute/assessments'
    | '/institute/classes'
    | '/institute/curriculum'
    | '/institute/reports'
    | '/institute/students'
    | '/institute/teachers'
    | '/onboarding/institute'
    | '/onboarding/parent'
    | '/onboarding/teacher'
    | '/parent/child'
    | '/parent/feedback'
    | '/parent/homework'
    | '/parent/learn'
    | '/parent/lessons'
    | '/parent/progress'
    | '/teacher/assessments'
    | '/teacher/blackboard'
    | '/teacher/curriculum'
    | '/teacher/language'
    | '/teacher/live'
    | '/teacher/more'
    | '/teacher/offline'
    | '/teacher/progress'
    | '/teacher/resources'
    | '/teacher/translate'
    | '/teacher/worksheets'
    | '/institute/'
    | '/parent/'
    | '/teacher/'
    | '/teacher/classrooms/$classroomId'
    | '/teacher/classrooms/new'
    | '/teacher/planner/plan'
    | '/teacher/students/$studentId'
    | '/teacher/classrooms/'
    | '/teacher/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RoleRoute: typeof RoleRoute
  SettingsRoute: typeof SettingsRoute
  InstituteAnalyticsRoute: typeof InstituteAnalyticsRoute
  InstituteAssessmentsRoute: typeof InstituteAssessmentsRoute
  InstituteClassesRoute: typeof InstituteClassesRoute
  InstituteCurriculumRoute: typeof InstituteCurriculumRoute
  InstituteReportsRoute: typeof InstituteReportsRoute
  InstituteStudentsRoute: typeof InstituteStudentsRoute
  InstituteTeachersRoute: typeof InstituteTeachersRoute
  OnboardingInstituteRoute: typeof OnboardingInstituteRoute
  OnboardingParentRoute: typeof OnboardingParentRoute
  OnboardingTeacherRoute: typeof OnboardingTeacherRoute
  ParentChildRoute: typeof ParentChildRoute
  ParentFeedbackRoute: typeof ParentFeedbackRoute
  ParentHomeworkRoute: typeof ParentHomeworkRoute
  ParentLearnRoute: typeof ParentLearnRoute
  ParentLessonsRoute: typeof ParentLessonsRoute
  ParentProgressRoute: typeof ParentProgressRoute
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherBlackboardRoute: typeof TeacherBlackboardRoute
  TeacherCurriculumRoute: typeof TeacherCurriculumRoute
  TeacherLanguageRoute: typeof TeacherLanguageRoute
  TeacherLiveRoute: typeof TeacherLiveRoute
  TeacherMoreRoute: typeof TeacherMoreRoute
  TeacherOfflineRoute: typeof TeacherOfflineRoute
  TeacherProgressRoute: typeof TeacherProgressRoute
  TeacherResourcesRoute: typeof TeacherResourcesRoute
  TeacherTranslateRoute: typeof TeacherTranslateRoute
  TeacherWorksheetsRoute: typeof TeacherWorksheetsRoute
  InstituteIndexRoute: typeof InstituteIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassroomsClassroomIdRoute: typeof TeacherClassroomsClassroomIdRoute
  TeacherClassroomsNewRoute: typeof TeacherClassroomsNewRoute
  TeacherPlannerPlanRoute: typeof TeacherPlannerPlanRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherClassroomsIndexRoute: typeof TeacherClassroomsIndexRoute
  TeacherPlannerIndexRoute: typeof TeacherPlannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/': {
      id: '/institute/'
      path: '/institute'
      fullPath: '/institute/'
      preLoaderRoute: typeof InstituteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/analytics': {
      id: '/institute/analytics'
      path: '/institute/analytics'
      fullPath: '/institute/analytics'
      preLoaderRoute: typeof InstituteAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/assessments': {
      id: '/institute/assessments'
      path: '/institute/assessments'
      fullPath: '/institute/assessments'
      preLoaderRoute: typeof InstituteAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/classes': {
      id: '/institute/classes'
      path: '/institute/classes'
      fullPath: '/institute/classes'
      preLoaderRoute: typeof InstituteClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/curriculum': {
      id: '/institute/curriculum'
      path: '/institute/curriculum'
      fullPath: '/institute/curriculum'
      preLoaderRoute: typeof InstituteCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/reports': {
      id: '/institute/reports'
      path: '/institute/reports'
      fullPath: '/institute/reports'
      preLoaderRoute: typeof InstituteReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/students': {
      id: '/institute/students'
      path: '/institute/students'
      fullPath: '/institute/students'
      preLoaderRoute: typeof InstituteStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/teachers': {
      id: '/institute/teachers'
      path: '/institute/teachers'
      fullPath: '/institute/teachers'
      preLoaderRoute: typeof InstituteTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/institute': {
      id: '/onboarding/institute'
      path: '/onboarding/institute'
      fullPath: '/onboarding/institute'
      preLoaderRoute: typeof OnboardingInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/parent': {
      id: '/onboarding/parent'
      path: '/onboarding/parent'
      fullPath: '/onboarding/parent'
      preLoaderRoute: typeof OnboardingParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/teacher': {
      id: '/onboarding/teacher'
      path: '/onboarding/teacher'
      fullPath: '/onboarding/teacher'
      preLoaderRoute: typeof OnboardingTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/child': {
      id: '/parent/child'
      path: '/parent/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof ParentChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/feedback': {
      id: '/parent/feedback'
      path: '/parent/feedback'
      fullPath: '/parent/feedback'
      preLoaderRoute: typeof ParentFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/homework': {
      id: '/parent/homework'
      path: '/parent/homework'
      fullPath: '/parent/homework'
      preLoaderRoute: typeof ParentHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/learn': {
      id: '/parent/learn'
      path: '/parent/learn'
      fullPath: '/parent/learn'
      preLoaderRoute: typeof ParentLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/lessons': {
      id: '/parent/lessons'
      path: '/parent/lessons'
      fullPath: '/parent/lessons'
      preLoaderRoute: typeof ParentLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/parent/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/teacher/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/blackboard': {
      id: '/teacher/blackboard'
      path: '/teacher/blackboard'
      fullPath: '/teacher/blackboard'
      preLoaderRoute: typeof TeacherBlackboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/curriculum': {
      id: '/teacher/curriculum'
      path: '/teacher/curriculum'
      fullPath: '/teacher/curriculum'
      preLoaderRoute: typeof TeacherCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/language': {
      id: '/teacher/language'
      path: '/teacher/language'
      fullPath: '/teacher/language'
      preLoaderRoute: typeof TeacherLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/live': {
      id: '/teacher/live'
      path: '/teacher/live'
      fullPath: '/teacher/live'
      preLoaderRoute: typeof TeacherLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/more': {
      id: '/teacher/more'
      path: '/teacher/more'
      fullPath: '/teacher/more'
      preLoaderRoute: typeof TeacherMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/offline': {
      id: '/teacher/offline'
      path: '/teacher/offline'
      fullPath: '/teacher/offline'
      preLoaderRoute: typeof TeacherOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/progress': {
      id: '/teacher/progress'
      path: '/teacher/progress'
      fullPath: '/teacher/progress'
      preLoaderRoute: typeof TeacherProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/resources': {
      id: '/teacher/resources'
      path: '/teacher/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof TeacherResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/translate': {
      id: '/teacher/translate'
      path: '/teacher/translate'
      fullPath: '/teacher/translate'
      preLoaderRoute: typeof TeacherTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/worksheets': {
      id: '/teacher/worksheets'
      path: '/teacher/worksheets'
      fullPath: '/teacher/worksheets'
      preLoaderRoute: typeof TeacherWorksheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classrooms/': {
      id: '/teacher/classrooms/'
      path: '/teacher/classrooms'
      fullPath: '/teacher/classrooms/'
      preLoaderRoute: typeof TeacherClassroomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classrooms/$classroomId': {
      id: '/teacher/classrooms/$classroomId'
      path: '/teacher/classrooms/$classroomId'
      fullPath: '/teacher/classrooms/$classroomId'
      preLoaderRoute: typeof TeacherClassroomsClassroomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classrooms/new': {
      id: '/teacher/classrooms/new'
      path: '/teacher/classrooms/new'
      fullPath: '/teacher/classrooms/new'
      preLoaderRoute: typeof TeacherClassroomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/planner/': {
      id: '/teacher/planner/'
      path: '/teacher/planner'
      fullPath: '/teacher/planner/'
      preLoaderRoute: typeof TeacherPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/planner/plan': {
      id: '/teacher/planner/plan'
      path: '/teacher/planner/plan'
      fullPath: '/teacher/planner/plan'
      preLoaderRoute: typeof TeacherPlannerPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/teacher/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RoleRoute: RoleRoute,
  SettingsRoute: SettingsRoute,
  InstituteAnalyticsRoute: InstituteAnalyticsRoute,
  InstituteAssessmentsRoute: InstituteAssessmentsRoute,
  InstituteClassesRoute: InstituteClassesRoute,
  InstituteCurriculumRoute: InstituteCurriculumRoute,
  InstituteReportsRoute: InstituteReportsRoute,
  InstituteStudentsRoute: InstituteStudentsRoute,
  InstituteTeachersRoute: InstituteTeachersRoute,
  OnboardingInstituteRoute: OnboardingInstituteRoute,
  OnboardingParentRoute: OnboardingParentRoute,
  OnboardingTeacherRoute: OnboardingTeacherRoute,
  ParentChildRoute: ParentChildRoute,
  ParentFeedbackRoute: ParentFeedbackRoute,
  ParentHomeworkRoute: ParentHomeworkRoute,
  ParentLearnRoute: ParentLearnRoute,
  ParentLessonsRoute: ParentLessonsRoute,
  ParentProgressRoute: ParentProgressRoute,
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherBlackboardRoute: TeacherBlackboardRoute,
  TeacherCurriculumRoute: TeacherCurriculumRoute,
  TeacherLanguageRoute: TeacherLanguageRoute,
  TeacherLiveRoute: TeacherLiveRoute,
  TeacherMoreRoute: TeacherMoreRoute,
  TeacherOfflineRoute: TeacherOfflineRoute,
  TeacherProgressRoute: TeacherProgressRoute,
  TeacherResourcesRoute: TeacherResourcesRoute,
  TeacherTranslateRoute: TeacherTranslateRoute,
  TeacherWorksheetsRoute: TeacherWorksheetsRoute,
  InstituteIndexRoute: InstituteIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassroomsClassroomIdRoute: TeacherClassroomsClassroomIdRoute,
  TeacherClassroomsNewRoute: TeacherClassroomsNewRoute,
  TeacherPlannerPlanRoute: TeacherPlannerPlanRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherClassroomsIndexRoute: TeacherClassroomsIndexRoute,
  TeacherPlannerIndexRoute: TeacherPlannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
